// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxLFXaQy1kgueDu41wPuM-hlUwA5V-lKY',
    appId: '1:502557711691:web:f6f758bf00f6dd98185cce',
    messagingSenderId: '502557711691',
    projectId: 'tiki-taka-scoreboard',
    authDomain: 'tiki-taka-scoreboard.firebaseapp.com',
    storageBucket: 'tiki-taka-scoreboard.firebasestorage.app',
    measurementId: 'G-DFFGL7RTMZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7zVg5DpF0b0HVbbmrErouDZMqcJyf_JI',
    appId: '1:502557711691:ios:132073a4de046f62185cce',
    messagingSenderId: '502557711691',
    projectId: 'tiki-taka-scoreboard',
    storageBucket: 'tiki-taka-scoreboard.firebasestorage.app',
    iosBundleId: 'com.pmorales.wearos.tikitaka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxLFXaQy1kgueDu41wPuM-hlUwA5V-lKY',
    appId: '1:502557711691:web:20b45a840237e586185cce',
    messagingSenderId: '502557711691',
    projectId: 'tiki-taka-scoreboard',
    authDomain: 'tiki-taka-scoreboard.firebaseapp.com',
    storageBucket: 'tiki-taka-scoreboard.firebasestorage.app',
    measurementId: 'G-905F3CBT25',
  );
}
